# Generated by Django 4.1 on 2022-08-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
